// this just happens to be the order that we exported the models animations in - see ASSETS.md
export enum PlayerAnimationIndices {
  Idle = 0,
  Walk = 1,
  Run = 2,
  Rotate180 = 3,
  StrafeLeft = 4,
  StrafeRight = 5,
  FireBow = 6,
  FireBlowpipe = 7,
  ThrowChinchompa = 8,
  ScytheIdle = 9,
  ScytheSwing = 10,
  SwordSlash = 11,
  Eat = 12,
  Dying = 13,
  CastSpell = 14,
  DragonClawsAttack = 15,
  TumekensShadowIdle = 16,
  TumekensShadowWalk = 17,
  TumekensShadowRun = 18,
  TumekensShadowAttack = 19,
  VenatorBowIdle = 20,
  VenatorBowWalk = 21,
  VenatorBowRun = 22,
  VenatorBowAttack = 23,
}
